log:
  level: INFO

accessLog:
  filePath: "/dev/stdout" # Forces access logs to print directly to docker logs

providers:
  docker:
    exposedByDefault: false
    network: traefik
  file:
    directory: /etc/traefik/config
    watch: true

api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          priority: 1000

  https:
    address: ":443"
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      email: best@fredagscafeen.dk
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
