services:
  garage:
    container_name: garage
    image: dxflrs/garage:v2.2.0
    restart: always
    environment:
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET}
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
      - GARAGE_METRICS_TOKEN=${GARAGE_METRICS_TOKEN}
    labels:
      - traefik.enable=true

      - traefik.http.routers.garage-api-wildcard.rule=Host(`*.s3.fredagscafeen.dk`)
      - traefik.http.routers.garage-api.rule=Host(`s3.fredagscafeen.dk`)
      - traefik.http.routers.garage-api-wildcard.service=garage-api
      - traefik.http.routers.garage-api.service=garage-api
      - traefik.http.services.garage-api.loadbalancer.server.port=3900
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
      - garage_data:/var/lib/garage
    networks:
      - traefik
  garage-webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    ports:
      - 3909:3909
    environment:
      API_ADMIN_KEY: ${GARAGE_ADMIN_TOKEN}
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
    labels:
      - traefik.enable=true

      - traefik.http.routers.garage-webui.rule=Host(`garage.fredagscafeen.dk`)
      - traefik.http.routers.garage-webui.service=garage-webui
      - traefik.http.routers.garage-webui.middlewares=auth
      - traefik.http.services.garage-webui.loadbalancer.server.port=3909
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  garage_data: